// API Keys and Configuration
export const CONFIG = {
  GOOGLE_SEARCH_API_KEY: 'AIzaSyDWqrMOjrjFHZKIlYS3gvB4gfTglwJlB00',
  GOOGLE_SEARCH_ENGINE_ID: '69329aa547ef54c96',
  UNSPLASH_API_KEY: 'yAIFvoWhNukc_9V4svgOmV-mF2PXbW-wImWgwZyiIy8',
  GEMINI_API_KEY: 'AIzaSyBQpM8ijAnrRWUUV-y7xXZZJysCaMSeHBE'
};